title: SimArena Documentation
tagline: AI-driven agent-based simulations
description: SimArena is a powerful toolkit for creating, configuring, and running simulations with multiple agents in various scenarios. It provides a robust foundation for AI research and development, with support for custom objectives, brains, weapons, and maps.
baseurl: /SimArena
url: https://arbyun.github.io
github_username: arbyun
paginate: 10
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme 